- name: Sediakan web server (Docker)
  hosts: node3
  become: true
  vars:
    docker_users: [ubuntu]
    site_title: Armada Infratify
    site_owner: Pasukan Platform
    web_port: 80
  roles:
    - geerlingguy.docker
  tasks:
    - name: Cipta folder web
      file:
        path: /opt/web
        state: directory

    - name: Cipta folder html
      file:
        path: /opt/web/html
        state: directory

    - name: Hantar index.html
      template:
        src: index.html.j2
        dest: /opt/web/html/index.html

    - name: Hantar config nginx
      template:
        src: nginx-site.conf.j2
        dest: /opt/web/default.conf

    - name: Hantar compose-web.yaml
      copy:
        src: compose-web.yaml
        dest: /opt/web/compose-web.yaml

    - name: Matikan nginx sistem lama (bebaskan port 80)
      service:
        name: nginx
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Naikkan container web
      command: docker compose -f compose-web.yaml up -d --force-recreate
      args:
        chdir: /opt/web
      register: web_up

    - name: Tunjuk hasil naikkan container
      command: docker compose -f compose-web.yaml ps
      args:
        chdir: /opt/web
      when: web_up is changed
